from django.core.management.base import BaseCommand

from mobiles.models import Mobile


MOBILES = [
    {
        "name": "iPhone 15",
        "brand": "Apple",
        "chip": "A16 Bionic",
        "ram": "6GB",
        "storage": "128GB",
        "battery": "3349mAh",
        "camera": "48MP + 12MP",
        "price": "22990000",
        "stock": 9,
        "description": "Mau iPhone pho bien de demo.",
        "image_url": "https://via.placeholder.com/300x200?text=iPhone+15",
    },
    {
        "name": "Samsung Galaxy S24",
        "brand": "Samsung",
        "chip": "Exynos 2400",
        "ram": "8GB",
        "storage": "256GB",
        "battery": "4000mAh",
        "camera": "50MP + 12MP + 10MP",
        "price": "20990000",
        "stock": 7,
        "description": "Flagship Android can bang.",
        "image_url": "https://via.placeholder.com/300x200?text=Galaxy+S24",
    },
    {
        "name": "Xiaomi 14",
        "brand": "Xiaomi",
        "chip": "Snapdragon 8 Gen 3",
        "ram": "12GB",
        "storage": "256GB",
        "battery": "4610mAh",
        "camera": "50MP Leica triple camera",
        "price": "17990000",
        "stock": 11,
        "description": "Flagship gia canh tranh.",
        "image_url": "https://via.placeholder.com/300x200?text=Xiaomi+14",
    },
    {
        "name": "OPPO Reno11",
        "brand": "OPPO",
        "chip": "Dimensity 8200",
        "ram": "12GB",
        "storage": "256GB",
        "battery": "5000mAh",
        "camera": "50MP + 32MP tele",
        "price": "12990000",
        "stock": 13,
        "description": "May tam trung camera dep.",
        "image_url": "https://via.placeholder.com/300x200?text=OPPO+Reno11",
    },
    {
        "name": "vivo V30",
        "brand": "vivo",
        "chip": "Snapdragon 7 Gen 3",
        "ram": "12GB",
        "storage": "256GB",
        "battery": "5000mAh",
        "camera": "50MP + 50MP",
        "price": "11990000",
        "stock": 12,
        "description": "Mau smartphone phu hop demo ecommerce.",
        "image_url": "https://via.placeholder.com/300x200?text=vivo+V30",
    },
    {
        "name": "Google Pixel 8",
        "brand": "Google",
        "chip": "Google Tensor G3",
        "ram": "8GB",
        "storage": "256GB",
        "battery": "4700mAh",
        "camera": "50MP + 12MP",
        "price": "19990000",
        "stock": 8,
        "description": "Smartphone voi AI camera tot nhat.",
        "image_url": "https://via.placeholder.com/300x200?text=Pixel+8",
    },
    {
        "name": "OnePlus 12",
        "brand": "OnePlus",
        "chip": "Snapdragon 8 Gen 3",
        "ram": "12GB",
        "storage": "256GB",
        "battery": "5400mAh",
        "camera": "50MP + 48MP + 48MP",
        "price": "18990000",
        "stock": 9,
        "description": "Smartphone toc do va hieu nang cao.",
        "image_url": "https://via.placeholder.com/300x200?text=OnePlus+12",
    },
    {
        "name": "Samsung Galaxy A54",
        "brand": "Samsung",
        "chip": "Exynos 1280",
        "ram": "6GB",
        "storage": "128GB",
        "battery": "5000mAh",
        "camera": "50MP + 12MP + 5MP",
        "price": "9990000",
        "stock": 15,
        "description": "Smartphone tam trung voi gia re.",
        "image_url": "https://via.placeholder.com/300x200?text=Galaxy+A54",
    },
    {
        "name": "Redmi Note 13",
        "brand": "Xiaomi",
        "chip": "Snapdragon 685",
        "ram": "6GB",
        "storage": "128GB",
        "battery": "5000mAh",
        "camera": "50MP + 8MP",
        "price": "7990000",
        "stock": 18,
        "description": "Smartphone gia re cho sinh vien.",
        "image_url": "https://via.placeholder.com/300x200?text=Redmi+Note+13",
    },
    {
        "name": "Realme 12",
        "brand": "Realme",
        "chip": "Snapdragon 7 Gen 1",
        "ram": "8GB",
        "storage": "256GB",
        "battery": "5000mAh",
        "camera": "50MP + 8MP",
        "price": "8990000",
        "stock": 16,
        "description": "Smartphone dang cap cao gia re.",
        "image_url": "https://via.placeholder.com/300x200?text=Realme+12",
    },
    {
        "name": "iPhone 14",
        "brand": "Apple",
        "chip": "A15 Bionic",
        "ram": "6GB",
        "storage": "128GB",
        "battery": "3280mAh",
        "camera": "12MP + 12MP",
        "price": "19990000",
        "stock": 8,
        "description": "iPhone phien ban trc voi gia re hon.",
        "image_url": "https://via.placeholder.com/300x200?text=iPhone+14",
    },
    {
        "name": "Samsung Galaxy S23",
        "brand": "Samsung",
        "chip": "Snapdragon 8 Gen 2",
        "ram": "8GB",
        "storage": "256GB",
        "battery": "3900mAh",
        "camera": "50MP + 10MP + 10MP",
        "price": "17990000",
        "stock": 7,
        "description": "Flagship Android gia re.",
        "image_url": "https://via.placeholder.com/300x200?text=Galaxy+S23",
    },
    {
        "name": "Xiaomi 13",
        "brand": "Xiaomi",
        "chip": "Snapdragon 8 Gen 2",
        "ram": "12GB",
        "storage": "256GB",
        "battery": "4500mAh",
        "camera": "50MP + 50MP Leica",
        "price": "16990000",
        "stock": 8,
        "description": "Flagship Xiaomi voi camera Leica.",
        "image_url": "https://via.placeholder.com/300x200?text=Xiaomi+13",
    },
    {
        "name": "OPPO Find X6",
        "brand": "OPPO",
        "chip": "Snapdragon 8 Gen 2",
        "ram": "12GB",
        "storage": "256GB",
        "battery": "5000mAh",
        "camera": "50MP + 50MP + 50MP",
        "price": "22990000",
        "stock": 6,
        "description": "Flagship OPPO voi 3 camera it.",
        "image_url": "https://via.placeholder.com/300x200?text=OPPO+Find+X6",
    },
    {
        "name": "vivo X90",
        "brand": "vivo",
        "chip": "Snapdragon 8 Gen 2",
        "ram": "12GB",
        "storage": "256GB",
        "battery": "4500mAh",
        "camera": "50MP + 50MP + 12MP",
        "price": "21990000",
        "stock": 6,
        "description": "Flagship vivo voi camera teles it.",
        "image_url": "https://via.placeholder.com/300x200?text=vivo+X90",
    },
    {
        "name": "Motorola Edge 50",
        "brand": "Motorola",
        "chip": "Snapdragon 7 Gen 1",
        "ram": "8GB",
        "storage": "256GB",
        "battery": "5000mAh",
        "camera": "50MP + 50MP",
        "price": "13990000",
        "stock": 10,
        "description": "Smartphone dam nhat vi tinh cam nghe.",
        "image_url": "https://via.placeholder.com/300x200?text=Motorola+Edge+50",
    },
    {
        "name": "Nothing Phone 2",
        "brand": "Nothing",
        "chip": "Snapdragon 8+ Gen 1",
        "ram": "12GB",
        "storage": "256GB",
        "battery": "4700mAh",
        "camera": "50MP + 50MP",
        "price": "15990000",
        "stock": 9,
        "description": "Smartphone with unique design.",
        "image_url": "https://via.placeholder.com/300x200?text=Nothing+Phone+2",
    },
    {
        "name": "ZTE Nubia Z60",
        "brand": "ZTE",
        "chip": "Snapdragon 8 Gen 2",
        "ram": "12GB",
        "storage": "256GB",
        "battery": "5100mAh",
        "camera": "50MP + 50MP ultra-wide",
        "price": "16990000",
        "stock": 8,
        "description": "Flagship ZTE voi camera it nieu.",
        "image_url": "https://via.placeholder.com/300x200?text=ZTE+Nubia+Z60",
    },
    {
        "name": "HTC U24",
        "brand": "HTC",
        "chip": "Snapdragon 8 Gen 2",
        "ram": "12GB",
        "storage": "256GB",
        "battery": "4850mAh",
        "camera": "50MP + 50MP",
        "price": "19990000",
        "stock": 7,
        "description": "Smartphone HTC voi design hoc tren.",
        "image_url": "https://via.placeholder.com/300x200?text=HTC+U24",
    },
    {
        "name": "Samsung Galaxy Z Fold 5",
        "brand": "Samsung",
        "chip": "Snapdragon 8 Gen 2",
        "ram": "12GB",
        "storage": "256GB",
        "battery": "4400mAh",
        "camera": "50MP + 10MP + 10MP",
        "price": "49990000",
        "stock": 3,
        "description": "Foldable smartphone cao cap.",
        "image_url": "https://via.placeholder.com/300x200?text=Galaxy+Z+Fold+5",
    },
    {
        "name": "Samsung Galaxy Z Flip 5",
        "brand": "Samsung",
        "chip": "Snapdragon 8 Gen 2",
        "ram": "8GB",
        "storage": "256GB",
        "battery": "3900mAh",
        "camera": "12MP + 12MP",
        "price": "32990000",
        "stock": 4,
        "description": "Flip foldable smartphone.",
        "image_url": "https://via.placeholder.com/300x200?text=Galaxy+Z+Flip+5",
    },
    {
        "name": "Tecno Camon 20",
        "brand": "Tecno",
        "chip": "Dimensity 7050",
        "ram": "8GB",
        "storage": "256GB",
        "battery": "5000mAh",
        "camera": "108MP + 2MP + 2MP",
        "price": "7990000",
        "stock": 14,
        "description": "Smartphone gia re camera it.",
        "image_url": "https://via.placeholder.com/300x200?text=Tecno+Camon+20",
    },
    {
        "name": "HONOR Magic 5",
        "brand": "HONOR",
        "chip": "Snapdragon 8+ Gen 1",
        "ram": "12GB",
        "storage": "256GB",
        "battery": "5100mAh",
        "camera": "54MP + 50MP + 50MP",
        "price": "24990000",
        "stock": 5,
        "description": "Flagship HONOR voi 3 camera it.",
        "image_url": "https://via.placeholder.com/300x200?text=HONOR+Magic+5",
    },
    {
        "name": "Infinix Zero 40",
        "brand": "Infinix",
        "chip": "MediaTek Dimensity 8200 Ultra",
        "ram": "12GB",
        "storage": "256GB",
        "battery": "5000mAh",
        "camera": "108MP + 50MP",
        "price": "9990000",
        "stock": 13,
        "description": "Smartphone tam trung gia re.",
        "image_url": "https://via.placeholder.com/300x200?text=Infinix+Zero+40",
    },
    {
        "name": "Poco F5",
        "brand": "Poco",
        "chip": "Snapdragon 7+ Gen 2",
        "ram": "12GB",
        "storage": "256GB",
        "battery": "5160mAh",
        "camera": "64MP + 8MP",
        "price": "10990000",
        "stock": 12,
        "description": "Smartphone co gia ban hang to.",
        "image_url": "https://via.placeholder.com/300x200?text=Poco+F5",
    },
    {
        "name": "Samsung Galaxy A75",
        "brand": "Samsung",
        "chip": "Exynos 1440",
        "ram": "8GB",
        "storage": "256GB",
        "battery": "5000mAh",
        "camera": "50MP + 12MP + 8MP",
        "price": "12990000",
        "stock": 11,
        "description": "Smartphone A-series voi dang cap cao.",
        "image_url": "https://via.placeholder.com/300x200?text=Galaxy+A75",
    },
    {
        "name": "OnePlus 11",
        "brand": "OnePlus",
        "chip": "Snapdragon 8 Gen 2",
        "ram": "12GB",
        "storage": "256GB",
        "battery": "5000mAh",
        "camera": "50MP + 50MP",
        "price": "17990000",
        "stock": 8,
        "description": "OnePlus flagship voi toc do cao.",
        "image_url": "https://via.placeholder.com/300x200?text=OnePlus+11",
    },
    {
        "name": "iQOO 12",
        "brand": "iQOO",
        "chip": "Snapdragon 8 Gen 3",
        "ram": "12GB",
        "storage": "256GB",
        "battery": "5000mAh",
        "camera": "50MP + 50MP + 50MP",
        "price": "22990000",
        "stock": 6,
        "description": "Gaming smartphone voi the nang cao.",
        "image_url": "https://via.placeholder.com/300x200?text=iQOO+12",
    },
    {
        "name": "Huawei Mate 60",
        "brand": "Huawei",
        "chip": "Kirin 9000S",
        "ram": "12GB",
        "storage": "512GB",
        "battery": "5110mAh",
        "camera": "40MP + 40MP Ultra + 12MP",
        "price": "24990000",
        "stock": 5,
        "description": "Smartphone flagship Huawei voi camera it.",
        "image_url": "https://via.placeholder.com/300x200?text=Huawei+Mate+60",
    },
]


class Command(BaseCommand):
    help = "Seed sample mobiles"

    def handle(self, *args, **options):
        created = 0
        for payload in MOBILES:
            _, was_created = Mobile.objects.get_or_create(
                name=payload["name"],
                defaults=payload,
            )
            created += int(was_created)

        self.stdout.write(self.style.SUCCESS(f"Seeded mobiles. Created: {created}"))
