from django.core.management.base import BaseCommand

from laptops.models import Laptop


LAPTOPS = [
    {
        "name": "Dell XPS 13",
        "brand": "Dell",
        "cpu": "Intel Core Ultra 7",
        "ram": "16GB",
        "storage": "512GB SSD",
        "screen": "13.4 inch FHD+",
        "price": "32990000",
        "stock": 8,
        "description": "Ultrabook cao cap cho cong viec va di chuyen.",
        "image_url": "https://via.placeholder.com/300x200?text=Dell+XPS+13",
    },
    {
        "name": "MacBook Air M3",
        "brand": "Apple",
        "cpu": "Apple M3",
        "ram": "16GB",
        "storage": "512GB SSD",
        "screen": "13.6 inch Liquid Retina",
        "price": "35990000",
        "stock": 6,
        "description": "Mau laptop mong nhe, thoi luong pin tot.",
        "image_url": "https://via.placeholder.com/300x200?text=MacBook+Air+M3",
    },
    {
        "name": "Lenovo ThinkPad X1 Carbon",
        "brand": "Lenovo",
        "cpu": "Intel Core i7",
        "ram": "16GB",
        "storage": "1TB SSD",
        "screen": "14 inch 2.8K OLED",
        "price": "38990000",
        "stock": 5,
        "description": "Do ben cao, phu hop doanh nghiep.",
        "image_url": "https://via.placeholder.com/300x200?text=ThinkPad+X1",
    },
    {
        "name": "ASUS ROG Zephyrus G14",
        "brand": "ASUS",
        "cpu": "AMD Ryzen 9",
        "ram": "32GB",
        "storage": "1TB SSD",
        "screen": "14 inch QHD 165Hz",
        "price": "42990000",
        "stock": 4,
        "description": "Laptop gaming hieu nang cao.",
        "image_url": "https://via.placeholder.com/300x200?text=ASUS+ROG+G14",
    },
    {
        "name": "HP Pavilion 15",
        "brand": "HP",
        "cpu": "Intel Core i5",
        "ram": "8GB",
        "storage": "512GB SSD",
        "screen": "15.6 inch FHD",
        "price": "18990000",
        "stock": 10,
        "description": "Laptop tam trung cho hoc tap va van phong.",
        "image_url": "https://via.placeholder.com/300x200?text=HP+Pavilion+15",
    },
    {
        "name": "MacBook Pro 14",
        "brand": "Apple",
        "cpu": "Apple M3 Pro",
        "ram": "18GB",
        "storage": "512GB SSD",
        "screen": "14.2 inch Liquid Retina XDR",
        "price": "58990000",
        "stock": 5,
        "description": "Laptop pro cho cac nha phat trien va thiet ke.",
        "image_url": "https://via.placeholder.com/300x200?text=MacBook+Pro+14",
    },
    {
        "name": "Dell Inspiron 15",
        "brand": "Dell",
        "cpu": "Intel Core i5",
        "ram": "8GB",
        "storage": "256GB SSD",
        "screen": "15.6 inch FHD",
        "price": "13990000",
        "stock": 12,
        "description": "Laptop gia ca hoc sinh va sinh vien.",
        "image_url": "https://via.placeholder.com/300x200?text=Dell+Inspiron+15",
    },
    {
        "name": "Lenovo IdeaPad 5",
        "brand": "Lenovo",
        "cpu": "AMD Ryzen 5",
        "ram": "8GB",
        "storage": "512GB SSD",
        "screen": "15.6 inch FHD",
        "price": "15990000",
        "stock": 9,
        "description": "Laptop da nang cho cong viec va giai tri.",
        "image_url": "https://via.placeholder.com/300x200?text=Lenovo+IdeaPad+5",
    },
    {
        "name": "ASUS VivoBook 15",
        "brand": "ASUS",
        "cpu": "AMD Ryzen 7",
        "ram": "16GB",
        "storage": "512GB SSD",
        "screen": "15.6 inch FHD",
        "price": "17990000",
        "stock": 8,
        "description": "Laptop sieu nhe va dal dung.",
        "image_url": "https://via.placeholder.com/300x200?text=ASUS+VivoBook+15",
    },
    {
        "name": "HP Envy 13",
        "brand": "HP",
        "cpu": "Intel Core i7",
        "ram": "16GB",
        "storage": "512GB SSD",
        "screen": "13.3 inch FHD",
        "price": "28990000",
        "stock": 6,
        "description": "Laptop thiet ke dep cho van phong.",
        "image_url": "https://via.placeholder.com/300x200?text=HP+Envy+13",
    },
    {
        "name": "Lenovo Legion 5",
        "brand": "Lenovo",
        "cpu": "Intel Core i7",
        "ram": "16GB",
        "storage": "512GB SSD",
        "screen": "15.6 inch 144Hz",
        "price": "29990000",
        "stock": 7,
        "description": "Laptop gaming tam trung.",
        "image_url": "https://via.placeholder.com/300x200?text=Lenovo+Legion+5",
    },
    {
        "name": "ASUS TUF Gaming F15",
        "brand": "ASUS",
        "cpu": "Intel Core i9",
        "ram": "32GB",
        "storage": "1TB SSD",
        "screen": "15.6 inch 144Hz",
        "price": "34990000",
        "stock": 5,
        "description": "Laptop gaming dan chac va manh me.",
        "image_url": "https://via.placeholder.com/300x200?text=ASUS+TUF+Gaming",
    },
    {
        "name": "Dell G15",
        "brand": "Dell",
        "cpu": "Intel Core i7",
        "ram": "16GB",
        "storage": "512GB SSD",
        "screen": "15.6 inch 165Hz",
        "price": "26990000",
        "stock": 8,
        "description": "Laptop gaming hieu suat cao.",
        "image_url": "https://via.placeholder.com/300x200?text=Dell+G15",
    },
    {
        "name": "Acer Aspire 5",
        "brand": "Acer",
        "cpu": "AMD Ryzen 5",
        "ram": "8GB",
        "storage": "512GB SSD",
        "screen": "15.6 inch FHD",
        "price": "14990000",
        "stock": 10,
        "description": "Laptop nea tang hieu qua chi phi.",
        "image_url": "https://via.placeholder.com/300x200?text=Acer+Aspire+5",
    },
    {
        "name": "Acer Swift 3",
        "brand": "Acer",
        "cpu": "Intel Core i5",
        "ram": "8GB",
        "storage": "512GB SSD",
        "screen": "14 inch FHD",
        "price": "16990000",
        "stock": 9,
        "description": "Laptop sieu nhe vung chay.",
        "image_url": "https://via.placeholder.com/300x200?text=Acer+Swift+3",
    },
    {
        "name": "HP Victus 15",
        "brand": "HP",
        "cpu": "Intel Core i7",
        "ram": "16GB",
        "storage": "512GB SSD",
        "screen": "15.6 inch 165Hz",
        "price": "27990000",
        "stock": 6,
        "description": "Laptop gaming gia pho bien.",
        "image_url": "https://via.placeholder.com/300x200?text=HP+Victus+15",
    },
    {
        "name": "MSI GE66 Raider",
        "brand": "MSI",
        "cpu": "Intel Core i9",
        "ram": "32GB",
        "storage": "1TB SSD",
        "screen": "15.6 inch 240Hz",
        "price": "39990000",
        "stock": 4,
        "description": "Laptop gaming cao cap cho esports.",
        "image_url": "https://via.placeholder.com/300x200?text=MSI+GE66+Raider",
    },
    {
        "name": "Razer Blade 15",
        "brand": "Razer",
        "cpu": "Intel Core i7",
        "ram": "16GB",
        "storage": "512GB SSD",
        "screen": "15.6 inch 144Hz",
        "price": "37990000",
        "stock": 5,
        "description": "Laptop gaming sieu nhe va manh.",
        "image_url": "https://via.placeholder.com/300x200?text=Razer+Blade+15",
    },
    {
        "name": "LG Gram 17",
        "brand": "LG",
        "cpu": "Intel Core i7",
        "ram": "16GB",
        "storage": "512GB SSD",
        "screen": "17 inch IPS",
        "price": "33990000",
        "stock": 5,
        "description": "Laptop sieu nhe voi man hinh lon.",
        "image_url": "https://via.placeholder.com/300x200?text=LG+Gram+17",
    },
    {
        "name": "Rog Flow X13",
        "brand": "ASUS",
        "cpu": "AMD Ryzen 7",
        "ram": "16GB",
        "storage": "512GB SSD",
        "screen": "13.4 inch FHD",
        "price": "29990000",
        "stock": 6,
        "description": "Laptop 2 trong 1 sieu nhe.",
        "image_url": "https://via.placeholder.com/300x200?text=ASUS+Flow+X13",
    },
    {
        "name": "MSI Modern 14",
        "brand": "MSI",
        "cpu": "Intel Core i5",
        "ram": "8GB",
        "storage": "512GB SSD",
        "screen": "14 inch FHD",
        "price": "19990000",
        "stock": 8,
        "description": "Laptop van phong sach chv va hieu qua.",
        "image_url": "https://via.placeholder.com/300x200?text=MSI+Modern+14",
    },
    {
        "name": "Dell Vostro 15",
        "brand": "Dell",
        "cpu": "Intel Core i5",
        "ram": "8GB",
        "storage": "256GB SSD",
        "screen": "15.6 inch FHD",
        "price": "12990000",
        "stock": 11,
        "description": "Laptop kinh doanh gia ca pho bien.",
        "image_url": "https://via.placeholder.com/300x200?text=Dell+Vostro+15",
    },
    {
        "name": "Lenovo Yoga 9",
        "brand": "Lenovo",
        "cpu": "Intel Core i7",
        "ram": "16GB",
        "storage": "512GB SSD",
        "screen": "14 inch OLED",
        "price": "32990000",
        "stock": 5,
        "description": "Laptop 2 trong 1 with OLED screen.",
        "image_url": "https://via.placeholder.com/300x200?text=Lenovo+Yoga+9",
    },
    {
        "name": "HP ZBook",
        "brand": "HP",
        "cpu": "Intel Core i9",
        "ram": "32GB",
        "storage": "1TB SSD",
        "screen": "17.3 inch 4K",
        "price": "61990000",
        "stock": 3,
        "description": "Workstation cho cac nha thiet ke.",
        "image_url": "https://via.placeholder.com/300x200?text=HP+ZBook",
    },
    {
        "name": "Dell Precision 15",
        "brand": "Dell",
        "cpu": "Intel Core i9",
        "ram": "32GB",
        "storage": "1TB SSD",
        "screen": "15.6 inch 4K",
        "price": "59990000",
        "stock": 3,
        "description": "Workstation cho cac nha phat trien.",
        "image_url": "https://via.placeholder.com/300x200?text=Dell+Precision",
    },
    {
        "name": "Lenovo ThinkPad T14",
        "brand": "Lenovo",
        "cpu": "Intel Core i5",
        "ram": "8GB",
        "storage": "256GB SSD",
        "screen": "14 inch FHD",
        "price": "18990000",
        "stock": 9,
        "description": "Laptop doanh nhan thua tin cay.",
        "image_url": "https://via.placeholder.com/300x200?text=ThinkPad+T14",
    },
    {
        "name": "Asus ExpertBook B1",
        "brand": "ASUS",
        "cpu": "Intel Core i5",
        "ram": "8GB",
        "storage": "256GB SSD",
        "screen": "14 inch FHD",
        "price": "17990000",
        "stock": 10,
        "description": "Laptop cho cac nhan vien kinh doanh.",
        "image_url": "https://via.placeholder.com/300x200?text=ASUS+ExpertBook",
    },
    {
        "name": "Samsung Galaxy Book3",
        "brand": "Samsung",
        "cpu": "Intel Core i5",
        "ram": "8GB",
        "storage": "256GB SSD",
        "screen": "15.6 inch FHD",
        "price": "19990000",
        "stock": 7,
        "description": "Laptop cua Samsung voi thiet ke dep.",
        "image_url": "https://via.placeholder.com/300x200?text=Galaxy+Book3",
    },
]


class Command(BaseCommand):
    help = "Seed sample laptops"

    def handle(self, *args, **options):
        created = 0
        for payload in LAPTOPS:
            _, was_created = Laptop.objects.get_or_create(
                name=payload["name"],
                defaults=payload,
            )
            created += int(was_created)

        self.stdout.write(self.style.SUCCESS(f"Seeded laptops. Created: {created}"))
