# Generated by Django 6.0.3 on 2026-03-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=120)),
                ('chip', models.CharField(max_length=120)),
                ('ram', models.CharField(max_length=64)),
                ('storage', models.CharField(max_length=64)),
                ('battery', models.CharField(max_length=64)),
                ('camera', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
