# Generated by Django 5.2.12 on 2026-03-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LaptopProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("brand", models.CharField(max_length=120)),
                ("cpu", models.CharField(max_length=120)),
                ("ram", models.CharField(max_length=64)),
                ("storage", models.CharField(max_length=64)),
                ("screen", models.CharField(max_length=120)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("stock", models.PositiveIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                ("image_url", models.URLField(blank=True)),
                ("status", models.CharField(choices=[("ACTIVE", "Active"), ("HIDDEN", "Hidden")], default="ACTIVE", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["name", "-created_at"]},
        ),
    ]
