# Generated by Django 5.2.12 on 2026-03-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("customer_id", models.PositiveIntegerField(db_index=True)),
                ("status", models.CharField(choices=[("ACTIVE", "Active"), ("CHECKED_OUT", "Checked out")], default="ACTIVE", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-updated_at"]},
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product_type", models.CharField(choices=[("LAPTOP", "Laptop"), ("CLOTHES", "Clothes")], max_length=20)),
                ("product_id", models.PositiveIntegerField()),
                ("product_name", models.CharField(max_length=255)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("subtotal", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("cart", models.ForeignKey(on_delete=models.CASCADE, related_name="items", to="carts.cart")),
            ],
            options={"ordering": ["id"], "unique_together": {("cart", "product_type", "product_id")}},
        ),
    ]
